#include "all.h"



/*
    DO NOT EDIT THIS FILE.
    THIS IS FOR THE SIMULATION TO WORK.
*/

void BTN_Init(void){
    microcontroller_pointer->activated    |= 0b1;
}

void SWT_Init(void){
    microcontroller_pointer->activated    |= 0b10;
}

void LED_Init(void){
    microcontroller_pointer->activated    |= 0b100;
}

void RGBLED_Init(void){
    // This function also affects the wait function, making the wait time 100x longer.
    // This is to simulate reality somewhat.
    microcontroller_pointer->activated    |= 0b1000;
    microcontroller_pointer->rgb_led_r = 0;
    microcontroller_pointer->rgb_led_g = 0;
    microcontroller_pointer->rgb_led_b = 0;
}

void RGBLED_Close(void){
    microcontroller_pointer->activated &= ~(1 << 3); // Sets 4th bit to 0;
}

void SSD_Init(void){
    microcontroller_pointer->activated |= 0b10000;
}

int SWT_GetValue(int x){
    if(!(microcontroller_pointer->activated & 2)){
        return -2;
    }

    if(x < 0 || x > 7){
        return -1;
    }

    return (microcontroller_pointer->switch_data >> (7-x)) & 1; // Originally left to right, now vice versa.
}

int BTN_GetValue(char name){
    if(!(microcontroller_pointer->activated & 0b1)){
        return -2;
    }
    int pos;
    switch (name)
    {
    case 'u': case 'U':
        pos = 0;
        break;
    case 'l': case 'L':
        pos = 1;
        break;
    case 'c': case 'C':
        pos = 2;
        break;
    case 'r': case 'R':
        pos = 3;
        break;
    case 'd': case 'D':
        pos = 4;
        break;
    
    default:
        return -1;
    }

    return (microcontroller_pointer->button_data >> pos) & 1;
}

void LED_SetValue(int x, int on_off){ // CHECK FOR ERRORS!
    x = 7 - x; // Originally left to right, now vice versa.

    if(x < 0 || x > 7){
        return;
    }
    if(!(microcontroller_pointer->activated & 0b100)){
        return;
    }

    if(on_off){
        microcontroller_pointer->led_data |= (1 << x);
    }
    else{
        microcontroller_pointer->led_data &= (~(1 << x));
    }
}

void RGBLED_SetValue(int red, int green, int blue){
    if(!(microcontroller_pointer->activated & 0b1000)){
        return;
    }
    
    if(red < 0) {red = 0;}
    if(red > 255) {red = 255;}

    if(green < 0) {green = 0;}
    if(green > 255) {green = 255;}
    
    if(blue < 0) {blue = 0;}
    if(blue > 255) {blue = 255;}

    microcontroller_pointer->rgb_led_r = red;
    microcontroller_pointer->rgb_led_g = green;
    microcontroller_pointer->rgb_led_b = blue;
}

void SSD_SetValue(int value){
    if(value<0){
        return;
    }
    if(!(microcontroller_pointer->activated & 0b10000)){
        return;
    }

    char hexadecimals[] = "0123456789ABCDEF";

    // Calculate 2 places in hexadecimal.
    microcontroller_pointer->ssd_data[0] = hexadecimals[(value%256)/16];
    microcontroller_pointer->ssd_data[1] = hexadecimals[(value%16)];
}

// Legacy support.
void wait(int usec){
    int rgb_led_lag_multiplier = 1;
    if((microcontroller_pointer->activated & 0b1000) >> 3){
        rgb_led_lag_multiplier = 100;
    }
    
    usleep(usec * rgb_led_lag_multiplier);
}

void DelayAprox10Us(int usec){
    wait(10 * usec);
}

// Audio
void BZR_Init(){
    microcontroller_pointer->activated |= 0b100000;
}

void BZR_SetValue(int freq, int amp, int on){
    if(!(microcontroller_pointer->activated & 0b100000)){
        if(on == 0) microcontroller_pointer->buzzer_pointer->playing = 0;
        return;
    }

    if(freq < 1) freq = 1;
    else if(freq > 1500) freq = 1500;

    if(amp > 1000) amp = 1000;
    else if(amp < 1) amp = 1;

    microcontroller_pointer->buzzer_pointer->period = microcontroller_pointer->buzzer_freq / freq;
    microcontroller_pointer->buzzer_pointer->amp = amp;
    microcontroller_pointer->buzzer_pointer->playing = on;
}

// Function that links the main simulator with simulation code.
EXPORT void linker(MicroController* pointer_to_global) { 
    microcontroller_pointer = pointer_to_global;
}