#include "micro_universal.h"

/*
    DO NOT EDIT THIS FILE.
    THIS IS FOR THE SIMULATION TO WORK.
*/

MicroController *microcontroller_pointer;

/*----------|
|    INIT   |
|----------*/

void BTN_Init(void);
void SWT_Init(void);
void LED_Init(void);

void RGBLED_Init(void);
void RGBLED_Close(void); // Close RGB LED

void SSD_Init(void);

/*----------|
|   Input   |
|----------*/

int SWT_GetValue(int x);
int BTN_GetValue(char name);

/*----------|
|   Output  |
|----------*/

void LED_SetValue(int x, int on_off);
void RGBLED_SetValue(int red, int green, int blue);
void SSD_SetValue(int value);

/*----------|
|   Other   |
|----------*/

void DelayAprox10Us(int usec);

/*----------|
|   Audio   |
|----------*/
void BZR_Init();
void BZR_SetValue(int freq, int amp, int on);